### ISSUE TITLE
CR: Display DStar UserMessage (TX Message) on dashboard

### ISSUE THREAD

**Issue by bboerdi** [n7tae/new-xlxd#10]
Hi Tom, 

would it be possible to display the DStar TX Message on the xlx dashboard?
maybe you can point me in to right directon to configure or implement that?

thanks in advance, robert/OE7BOE

**Comment by n7tae** [comment]
Hi Robert,

Sorry, no. Generally only data in the first (Header) packet is available to the reflector dashboard.

The 20-character DStar text message is serially encoded into the voice packet stream, in an area called the "slow data" stream. There are also several other things in this "slow data" stream, including GPS coordinates as well as a text representation of the stream header. It would be a lot of extra code that would have to be added to the three DStar protocols (DPlus, DCS and DExtra).

**Comment by bboerdi** [comment]
Hi Tom,

thanks for your fast response and background-info.

Cheers, Robert/OE7BOE

Von: Tom Early ***@***.***>
Datum: Samstag, 16. Dezember 2023 um 00:32
An: n7tae/new-xlxd ***@***.***>
Cc: Robert Schneider ***@***.***>, Author ***@***.***>
Betreff: Re: [n7tae/new-xlxd] CR: Display DStar UserMessage (TX Message) on dashboard (Issue #10)

Hi Robert,

Sorry, no. Generally only data in the first (Header) packet is available to the reflector dashboard.

The 20-character DStar text message is serially encoded into the voice packet stream, in an area called the "slow data" stream. There are also several other things in this "slow data" stream, including GPS coordinates as well as a text representation of the stream header. It would be a lot of extra code that would have to be added to the three DStar protocols (DPlus, DCS and DExtra).
