### ISSUE TITLE
Multiple connections from the same IP

### ISSUE THREAD

**Issue by iamsi** [n7tae/new-xlxd#2]
Hi Tom, 

I'm back again.

I'm not sure if it's intentional but this fork doesn't allow multiple connections from the same callsign. Caused me some confusion with our cross mode links.

if it's intentional I'd like to submit a documentation PR to mention it.

Cheers!

Simon

**Comment by n7tae** [comment]
Sure, go ahead.

Is this different behavior than the base LX3JL repo?

**Comment by yuvelq** [comment]
Hi Tom,

I confirm this issue the XLX allows multiple connections with the same ID but in the dashboard you can see like only one client is connected, in my case to the module C, the audio that comes from the clients that are supposedly connected to the module A and B is heard through the module C, all these clients are using mmdvm protocol, additionally I can connect one more client using YSF protocol, the XLX allows the connection and the dashboard shows that connection too so it’s working fine.

Regards,
Christian OA4DOA

**Comment by iamsi** [comment]
it's even more strange than that :) if you have d-star as the second connection it'll constantly connect and reconnect. so it kind of allows multiple connections but they are weird. I have a fix I'm trying that allows the connections the same as upstream.  [EDIT] I've cleaned up my local repo and submitted the PR.

**Comment by iamsi** [comment]
The Branch here "Issue#2" fixes this. Thanks Tom! Edit now in master :)
