### ISSUE TITLE
rconfig Does Not Update Callsign

### ISSUE THREAD

**Issue by W4JEW** [n7tae/new-xlxd#7]
I ran the rconfig script according to the instructions in the README file - I have one question and am running into one issue:

1. This is probably a dumb question - how do you quit while SAVING changes? There are options to quit without saving and unset a value, but no options to quit while saving.

2. The value for the Reflector Callsign field never gets updated. All other fields update with the values I enter as expected. Any thoughts as to why this is happening?

I've tried running the script as the same user account I used to clone the repository and as root. The behavior is the same. It's not a permissions issue.

When initially running rconfig, I see the following:

```
        Reflector Configuration, Version #200821

     ******* REFLECTOR ********
cs : Reflector Callsign     = CHNGME <DEFAULT>
nm : Number of Modules      = 26 <DEFAULT>
g3 : Icom G3 Support        = false <DEFAULT>
     ******* ADDRESSES ********
i4 : IPv4 Listen Address    = none <DEFAULT>
i6 : IPv6 Listen Address    = none <DEFAULT>
     ******* DEBUGGING ********
db : Debugging Support      = false <DEFAULT>

q  : Quit without saving
u  : Unset the value of <key> (revert to the default value).

Please input <key> <value> - omit value to toggle a true/false :
```

I try to set my callsign by entering the following:

```
cs W1ABC (then enter)
```
_that's just an example callsign - not my actual callsign_

The value of the field never changes from CHNGME <DEFAULT>

I can update any other options that reflect whatever values I set, but CHNGME never gets updated.

```
        Reflector Configuration, Version #200821

     ******* REFLECTOR ********
cs : Reflector Callsign     = CHNGME <DEFAULT>
nm : Number of Modules      = 2
g3 : Icom G3 Support        = true
     ******* ADDRESSES ********
i4 : IPv4 Listen Address    = 192.168.1.10
i6 : IPv6 Listen Address    = none
     ******* DEBUGGING ********
db : Debugging Support      = true

q  : Quit without saving
u  : Unset the value of <key> (revert to the default value).

Please input <key> <value> - omit value to toggle a true/false :
```

**Comment by n7tae** [comment]
`Reflector Callsign` has to be either `XRF???` or `XLX???` where ? is a letter or number. Then you will see an option to write the necessary files.
