### ISSUE TITLE
Unable to compile ambed

### ISSUE THREAD

**Issue by W4JEW** [n7tae/new-xlxd#8]
I am attempting to install new-xlxd on Debian 11 Bullseye (x64).

I can successfully compile the binary for ambedtest, but am unable to compile the binary for ambed.

```
root@xlxd-nextgen:/root/new-xlxd/ambed# make
Makefile:3: configure.mk: No such file or directory
make: *** No rule to make target 'configure.mk'.  Stop.
```

I have all of the packages installed as listed in new-xlxd/README.md - including build-essential, git, and g++

From what I can tell, it looks like the version of ambed that is included in this repository is older than the version in the mainline xlxd repository. Can you confirm? Did you intend for users to be able to compile ambed? Or is it still part of your repository only because it was part of the original xlxd repository?

**Comment by n7tae** [comment]
`rconfig` writes the `configure.mk` file.

**Comment by W4JEW** [comment]
Thank you for getting back to me quickly on both issues I raised. This is a great project. It's nice to see someone extend the functionality of a project that's effectively stagnated for a long time. 73
