### ISSUE TITLE
Config files instead of hard coded

### ISSUE THREAD

**Issue by coolacid** [n7tae/new-xlxd#9]
Is there any chance of moving towards configuration files as opposed to hard coded values?

**Comment by n7tae** [comment]
Sorry, I'm not actively developing new-xlxd as it had been superseded by urfd. It uses a config file and it supports new modes, like M17.

**Comment by coolacid** [comment]
Makes total sense. I found urfd after creating the ticket. Alas, the tcd being local only is a non-starter for me. Will be keeping an eye tho.
